export const ASTRA_LIMITS={job:12000,context:30000,message:60000,toolOutput:24000,report:12000,event:500};
export const ASTRA_STALE_MS=15*60*1000;
export function compactForModel(content,artifactRef,limit=ASTRA_LIMITS.job){const value=String(content||'');if(value.length<=limit)return{content:value,artifactRefs:[]};const marker=`\n\n[Full content: ${artifactRef}]`;return{content:`${value.slice(0,Math.max(0,limit-marker.length))}${marker}`,artifactRefs:[artifactRef]};}
export function compactAstraPayload(input={},artifactRef){const job=compactForModel(input.job,artifactRef,ASTRA_LIMITS.job),context=compactForModel(input.context,artifactRef,ASTRA_LIMITS.context);return{...input,job:job.content,context:context.content,artifactRefs:Array.from(new Set([...job.artifactRefs,...context.artifactRefs]))};}
export function assertAstraPayload(input={}){for(const [field,limit] of Object.entries({job:ASTRA_LIMITS.job,context:ASTRA_LIMITS.context})){const size=String(input[field]||'').length;if(size>limit)throw new Error(`${field} exceeds the ${limit}-character limit.`);}return input;}
export function reportedJobState(job,now=Date.now()){if(!job||!job.status)return'unknown';if(job.status==='running'&&now-new Date(job.heartbeatAt||job.startedAt||0).getTime()>ASTRA_STALE_MS)return'unknown';if(job.status==='completed'&&!job.resultRecordedAt)return'unknown';return['queued','running','blocked','failed','completed','cancelled'].includes(job.status)?job.status:'unknown';}
export function failureUpdate(job,error,now=new Date().toISOString()){return{status:'failed',failedAt:now,heartbeatAt:now,error:String(error||'Execution failed.').slice(0,1000),lastCheckpoint:job?.lastCheckpoint||'',currentStep:job?.currentStep||0,currentStepLabel:job?.currentStepLabel||'',changedFiles:job?.changedFiles||[],checks:job?.checks||[],nextStep:job?.nextStep||'Resume from the last checkpoint.'};}
export function resumeHandoff(previous,repoState){const checkpoint=previous?.lastCheckpoint||'No prior checkpoint.';return`Repository inspection: ${repoState.branch}@${repoState.headSha}; base ${repoState.baseCommitSha}; relevant changed files: ${(repoState.changedFiles||[]).join(', ')||'none'}. Previous checkpoint: ${checkpoint}. Next unfinished step: ${previous?.nextStep||'Inspect the requested scope and continue only unfinished work.'}`;}
export function scheduledLabel(persisted,count){return persisted?`${count} specialist job${count===1?'':'s'} scheduled.`:'Scheduling failed; no job was reported as scheduled.';}
export function managerPlanEffect(jobs=[],replacePending=false){return{enqueue:jobs.length>0,cancelPending:jobs.length>0&&replacePending};}