import { Contract,Interface,formatEther,formatUnits,parseEther,parseUnits } from "ethers";
import { base44 } from "@/api/base44Client";
import { CURVE_ABI,TOKEN_ABI,PAIR_ABI } from "@/lib/kydosContracts";
import { useWallet } from "@/lib/WalletContext";

export default function useKydosTrade(token){
  const wallet=useWallet();
  const contracts=async()=>{const signer=await wallet.signer();return {signer,curve:new Contract(token.curve_address,CURVE_ABI,signer),coin:new Contract(token.token_address,TOKEN_ABI,signer)};};
  const trade=async(side,amount)=>{const {signer,curve,coin}=await contracts();const trader=(await signer.getAddress()).toLowerCase();let tx;if(side==="buy"){const value=parseEther(amount);const expected=await curve.quoteBuy(value);tx=await curve.buy((expected*99n)/100n,{value});}else{const units=parseUnits(amount,18);if(await coin.allowance(trader,token.curve_address)<units)await (await coin.approve(token.curve_address,units)).wait();const expected=await curve.quoteSell(units);tx=await curve.sell(units,(expected*99n)/100n);}const receipt=await tx.wait();const iface=new Interface(CURVE_ABI);const event=receipt.logs.map((log)=>{try{return iface.parseLog(log);}catch{return null;}}).find((log)=>log?.name===(side==="buy"?"Buy":"Sell"));if(!event)throw new Error("Trade event was not found");const hood=Number(formatEther(side==="buy"?event.args.ethIn:event.args.ethOut));const tokens=Number(formatUnits(side==="buy"?event.args.tokensOut:event.args.tokensIn,18));const [reserve,sold,price]=await Promise.all([curve.reserve(),curve.tokensSold(),curve.currentPrice()]);return {trader,hood,tokens,reserve:Number(formatEther(reserve)),sold:Number(formatUnits(sold,18)),price:Number(formatEther(price)),hash:receipt.hash,block:receipt.blockNumber};};
  const graduate=async()=>{const {curve,signer}=await contracts();const receipt=await (await curve.graduate()).wait();const iface=new Interface(CURVE_ABI);const event=receipt.logs.map((log)=>{try{return iface.parseLog(log);}catch{return null;}}).find((log)=>log?.name==="Graduated");if(!event)throw new Error("Graduation event was not found");const pair=String(event.args.pair).toLowerCase();const pairContract=new Contract(pair,PAIR_ABI,signer);const token0=String(await pairContract.token0()).toLowerCase();const [config]=await base44.entities.KydosConfig.filter({active:true},"-deployed_at",1);await base44.entities.RhPool.create({address:pair,token_address:token.token_address,venue:"uniswap_v2",token0,token1:String(await pairContract.token1()).toLowerCase(),base_is_token0:token0===token.token_address,quote_address:config.weth_address,quote_symbol:"WETH",quote_decimals:18,base_decimals:18,launchpad_verified:true,active:true,discovered_at:Date.now(),trust_status:"TRUSTED"});return pair;};
  return {trade,graduate};
}