import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { secrets, waitUntil } from 'base44:runtime';
import { runSpecialist } from '../../shared/astraCrew.ts';
import { inspectRepoState } from '../../shared/astraGithub.ts';
import { ASTRA_LIMITS, automaticRetryPlan, canTrustRecordedResults, failureUpdate, resumeHandoff, selectNextRunnable } from '../../shared/astraOrchestration.ts';
import { validateFinding, assertAuditWrite } from '../../shared/astraAuditGate.ts';
import { resolveToolsModel } from '../../shared/astraOpenAi.ts';
const ASTRA_WORKER_VERSION='2026-09-21-time-budget-continuation-v1';
class AstraJobCancelledError extends Error { constructor(){super('Job cancelled manually.');this.name='AstraJobCancelledError';} }
function dispatchQueued(base44,job){console.info('astra dispatch requested',{jobId:job.jobUid||job.id,recordId:job.id,attempt:job.attempt||1});waitUntil(base44.functions.invoke('astraWorker',{jobId:job.id,runToken:job.runToken}).catch(error=>console.error('astra dispatch failed',job.id,error?.message||error)));}
async function queueNext(service,excludedBatchId=''){const executors=await service.entities.AstraJob.filter({status:{$in:['queued','running']}},'created_date',10);if(executors.length)return null;const blocked=await service.entities.AstraJob.filter({status:'blocked'},'created_date',100);const next=selectNextRunnable(blocked,excludedBatchId);if(!next)return null;console.info('astra queue selected',{jobId:next.jobUid||next.id,recordId:next.id,batchId:next.batchId});return service.entities.AstraJob.update(next.id,{status:'queued',queuedAt:new Date().toISOString(),blocker:'',nextStep:'Execution is ready to begin.'});}
const detailFor=(name,args)=>name==='readFile'||name==='commitFile'?{detailType:'file',detailRef:JSON.stringify({repo:args.repo,path:args.path})}:name==='listRepoTree'?{detailType:'tree',detailRef:JSON.stringify({repo:args.repo})}:name==='readReference'?{detailType:'reference',detailRef:JSON.stringify({id:args.id})}:{detailType:'none',detailRef:''};
export default async function(req:Request):Promise<Response>{const base44=createClientFromRequest(req);const input=await req.json().catch(()=>({}));let job;
 try{
  job=await base44.asServiceRole.entities.AstraJob.get(String(input.jobId||'')).catch(()=>null);if(!job)return Response.json({error:'Job not found.'},{status:404});
  const user=await base44.auth.me().catch(()=>null);const tokenAuthorized=String(input.runToken||'')===job.runToken;if(user?.role!=='admin'&&!tokenAuthorized){console.warn('astra worker authorization rejected',{jobId:job.jobUid||job.id});return Response.json({error:'Forbidden.',workerVersion:ASTRA_WORKER_VERSION},{status:403});}
  console.info('astra worker authorized',{jobId:job.jobUid||job.id,status:job.status,via:user?.role==='admin'?'admin':'runToken',workerVersion:ASTRA_WORKER_VERSION});
  if(input.dispatchOnly===true){if(job.status!=='queued')return Response.json({ok:true,status:job.status||'unknown',workerVersion:ASTRA_WORKER_VERSION});dispatchQueued(base44,job);return Response.json({ok:true,status:'dispatch_requested',jobId:job.jobUid,workerVersion:ASTRA_WORKER_VERSION},{status:202});}
  if(job.status!=='queued')return Response.json({ok:true,status:job.status||'unknown',workerVersion:ASTRA_WORKER_VERSION});
  const apiKey=secrets.get('ASTRA_OPENAI_API_KEY');if(!apiKey)return Response.json({error:'Astra credentials are missing.'},{status:503});
  const {accessToken:githubToken}=await base44.asServiceRole.connectors.getConnection('github');const service=base44.asServiceRole,started=Date.now(),now=new Date().toISOString();
  const repoState=await inspectRepoState(githubToken,'doji0x/kydosv1',job.branch||'astra/latest');
  const previous=job.resumeFromJobId?await service.entities.AstraJob.get(job.resumeFromJobId).catch(()=>null):null;
  const handoff=resumeHandoff(previous,repoState),trustedResults=canTrustRecordedResults(previous,repoState);
  await service.entities.AstraJob.update(job.id,{status:'running',startedAt:now,heartbeatAt:now,baseCommitSha:repoState.baseCommitSha,headCommitSha:repoState.headSha,changedFiles:repoState.changedFiles||[],currentStep:0,currentStepLabel:'Repository state inspected',lastCheckpoint:handoff,checks:trustedResults?(previous?.checks||[]):[],artifactRefs:(repoState.changedFiles||[]).slice(0,100),nextStep:'Continue from the last verified state.',blocker:'',error:''});
  const writeMessage=data=>service.entities.AstraMessage.create({conversationId:job.conversationId,role:'activity',jobId:job.id,specialistRole:job.role,repo:'doji0x/kydosv1',...data});
  await writeMessage({activityType:'specialist_start',status:'running',content:`${job.jobUid} started`,summary:`${job.role} started after repository inspection`,detail:handoff.slice(0,ASTRA_LIMITS.event)});
  const decision=job.auditDecisionId?await service.entities.AstraAuditIssue.get(job.auditDecisionId):null;let issueCount=0,step=0,changedFiles=[...(repoState.changedFiles||[])],checks=trustedResults?[...(previous?.checks||[])]:[];
  const recordAuditIssue=async args=>{const fields=validateFinding(args);const issue=await service.entities.AstraAuditIssue.create({...fields,conversationId:job.conversationId,status:'pending',...(decision?{parentIssueId:decision.id}:{})});issueCount++;if(decision)await service.entities.AstraAuditIssue.update(decision.id,{supersededBy:issue.id});return{recorded:true,issueId:issue.id};};
  const assertNotCancelled=async()=>{const current=await service.entities.AstraJob.get(job.id);if(current.status==='cancelled')throw new AstraJobCancelledError();};
  const log=async item=>{await assertNotCancelled();step=Math.max(step+1,item.step||0);if(item.changedFile&&!changedFiles.includes(item.changedFile))changedFiles.push(item.changedFile);if(item.toolName)checks=[...checks,{name:item.toolName,result:item.failed?`failed: ${item.error}`:'passed'}].slice(-30);const checkpoint=String(item.detail||item.label).slice(0,ASTRA_LIMITS.event);const stamp=new Date().toISOString();await service.entities.AstraJob.update(job.id,{heartbeatAt:stamp,currentStep:step,currentStepLabel:String(item.label||'Working').slice(0,200),lastCheckpoint:checkpoint,changedFiles,artifactRefs:changedFiles.slice(0,100),checks,blocker:item.failed?String(item.error||'Blocked').slice(0,500):'',nextStep:String(item.nextStep||'Continue unfinished work.').slice(0,500),headCommitSha:item.changedFile?String(checkpoint.split('→')[1]||repoState.headSha).trim():repoState.headSha});const ref=detailFor(item.toolName,item.args||{});await writeMessage({activityType:item.kind||'tool',status:item.failed?'failed':'running',content:String(item.label||'Progress').slice(0,200),summary:checkpoint,detail:'',durationMs:item.durationMs||0,toolName:item.toolName||'',...ref});};
  const outcome=await runSpecialist({apiKey,toolsModel:resolveToolsModel(secrets.get('ASTRA_TOOLS_MODEL')),githubToken,base44:service,role:job.role,job:job.job,context:job.context||'',log,beforeWrite:args=>assertAuditWrite(service,job.conversationId,decision,args),recordAuditIssue,repoState,previousCheckpoint:previous?.lastCheckpoint||'',startedAt:started,softBudgetMs:270000});
  await assertNotCancelled();
  if(outcome?.timeBudgetExceeded){
   const completedAt=new Date().toISOString(),durationMs=Date.now()-started,current=await service.entities.AstraJob.get(job.id),summary='Time budget reached; linked continuation queued from the latest checkpoint.';
   await service.entities.AstraJob.update(job.id,{status:'completed',report:summary,summary,resultRecordedAt:completedAt,completedAt,heartbeatAt:completedAt,durationMs,currentStepLabel:'Time-budget continuation queued',lastCheckpoint:current.lastCheckpoint||outcome.lastCheckpoint,nextStep:'Continue in the linked continuation job.',blocker:''});
   const continuation=await service.entities.AstraJob.create({jobUid:crypto.randomUUID(),requestId:job.requestId,conversationId:job.conversationId,batchId:job.batchId,milestoneId:job.milestoneId||job.batchId,turn:job.turn,role:job.role,scope:job.scope,job:job.job,context:job.context||'',status:'queued',position:job.position,attempt:current.attempt||1,maxAttempts:current.maxAttempts||3,runToken:crypto.randomUUID(),auditDecisionId:job.auditDecisionId,resumeFromJobId:job.id,branch:job.branch||'astra/latest',baseCommitSha:current.baseCommitSha||repoState.baseCommitSha,headCommitSha:current.headCommitSha||repoState.headSha,queuedAt:completedAt,currentStep:current.currentStep||outcome.currentStep||0,currentStepLabel:'Continuation queued from time budget',lastCheckpoint:current.lastCheckpoint||outcome.lastCheckpoint,changedFiles:current.changedFiles||changedFiles,checks:current.checks||checks,blocker:'',nextStep:'Continue from checkpoint.',artifactRefs:current.artifactRefs||changedFiles.slice(0,100)});
   await writeMessage({activityType:'specialist_complete',status:'completed',content:`${job.jobUid} checkpointed`,summary,durationMs});
   dispatchQueued(base44,continuation);
   return Response.json({ok:true,jobId:job.jobUid,status:'continued',continuationJobId:continuation.jobUid,workerVersion:ASTRA_WORKER_VERSION},{status:202});
  }
  const report=String(outcome||'No report.'),completedAt=new Date().toISOString(),durationMs=Date.now()-started,summary=report.slice(0,ASTRA_LIMITS.event);
  await service.entities.AstraJob.update(job.id,{status:'completed',report:report.slice(0,ASTRA_LIMITS.report),summary,resultRecordedAt:completedAt,completedAt,heartbeatAt:completedAt,durationMs,currentStepLabel:'Result recorded',lastCheckpoint:summary,nextStep:'No unfinished step.',blocker:''});
  await writeMessage({activityType:'report',status:'completed',content:summary,summary:`${job.role} result recorded`,durationMs});
  await writeMessage({activityType:'specialist_complete',status:'completed',content:`${job.jobUid} completed`,summary:`Completed in ${(durationMs/1000).toFixed(1)}s`,durationMs});
  if(decision&&job.role==='audit'&&!issueCount)await service.entities.AstraAuditIssue.update(decision.id,{status:'resolved',runStatus:'completed',runError:''});
  const next=await queueNext(service);if(next)dispatchQueued(base44,next);
  return Response.json({ok:true,jobId:job.jobUid,status:'completed',workerVersion:ASTRA_WORKER_VERSION});
 }catch(error){if(job){const service=base44.asServiceRole,current=await service.entities.AstraJob.get(job.id).catch(()=>job);if(error instanceof AstraJobCancelledError||current.status==='cancelled'){await service.entities.AstraMessage.create({conversationId:job.conversationId,role:'activity',jobId:job.id,specialistRole:job.role,activityType:'specialist_failed',status:'failed',content:`${job.jobUid||job.id} cancelled`,summary:'Stopped manually by an administrator.',repo:'doji0x/kydosv1'}).catch(()=>{});const next=await queueNext(service).catch(()=>null);if(next)dispatchQueued(base44,next);return Response.json({ok:true,jobId:job.jobUid,status:'cancelled',workerVersion:ASTRA_WORKER_VERSION});}const plan=automaticRetryPlan(current,error);const update={...failureUpdate(current,error),durationMs:current.startedAt?Date.now()-new Date(current.startedAt).getTime():0,blocker:String(error.message).slice(0,500)};await service.entities.AstraJob.update(job.id,update).catch(()=>{});let retry=null;if(plan.retry){retry=await service.entities.AstraJob.create({jobUid:crypto.randomUUID(),requestId:`${current.requestId}:retry:${plan.nextAttempt}`,conversationId:current.conversationId,batchId:current.batchId,milestoneId:current.milestoneId||current.batchId,turn:current.turn,role:current.role,scope:current.scope,job:current.job,context:current.context||'',status:'queued',position:current.position,attempt:plan.nextAttempt,maxAttempts:plan.maxAttempts,runToken:crypto.randomUUID(),auditDecisionId:current.auditDecisionId,resumeFromJobId:current.id,branch:current.branch||'astra/latest',baseCommitSha:current.baseCommitSha,headCommitSha:current.headCommitSha,queuedAt:new Date().toISOString(),currentStep:current.currentStep||0,currentStepLabel:'Retry queued from checkpoint',lastCheckpoint:current.lastCheckpoint||'',changedFiles:current.changedFiles||[],checks:current.checks||[],blocker:'',nextStep:plan.reason,artifactRefs:current.artifactRefs||[]}).catch(()=>null);}else{const remaining=await service.entities.AstraJob.filter({batchId:current.batchId,status:'blocked'},'created_date',100);if(remaining.length)await service.entities.AstraJob.bulkUpdate(remaining.map(x=>({id:x.id,blocker:`Milestone blocked: ${plan.reason}`,nextStep:'Resolve the blocker, then explicitly retry the milestone.'}))).catch(()=>{});const next=await queueNext(service,current.batchId).catch(()=>null);if(next)dispatchQueued(base44,next);}if(retry)dispatchQueued(base44,retry);await service.entities.AstraMessage.create({conversationId:job.conversationId,role:'activity',jobId:job.id,specialistRole:job.role,activityType:'specialist_failed',status:'failed',content:`${job.jobUid||job.id} failed`,summary:retry?`Attempt ${current.attempt||1} failed; retry ${plan.nextAttempt} queued from checkpoint.`:`${String(error.message).slice(0,300)} ${plan.reason}`,durationMs:update.durationMs,repo:'doji0x/kydosv1'}).catch(()=>{});}return Response.json({error:error.message,workerVersion:ASTRA_WORKER_VERSION},{status:500});}
}