import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { secrets } from 'base44:runtime';
import { runSpecialist } from '../../shared/astraCrew.ts';
import { inspectRepoState } from '../../shared/astraGithub.ts';
import { ASTRA_LIMITS, failureUpdate, resumeHandoff } from '../../shared/astraOrchestration.ts';
import { validateFinding, assertAuditWrite } from '../../shared/astraAuditGate.ts';
import { resolveToolsModel } from '../../shared/astraOpenAi.ts';
const detailFor=(name,args)=>name==='readFile'||name==='commitFile'?{detailType:'file',detailRef:JSON.stringify({repo:args.repo,path:args.path})}:name==='listRepoTree'?{detailType:'tree',detailRef:JSON.stringify({repo:args.repo})}:name==='readReference'?{detailType:'reference',detailRef:JSON.stringify({id:args.id})}:{detailType:'none',detailRef:''};
export default async function(req:Request):Promise<Response>{const base44=createClientFromRequest(req);const input=await req.json().catch(()=>({}));let job;
 try{
  job=await base44.asServiceRole.entities.AstraJob.get(String(input.jobId||'')).catch(()=>null);if(!job)return Response.json({error:'Job not found.'},{status:404});
  const user=await base44.auth.me().catch(()=>null);if(user?.role!=='admin'&&String(input.runToken||'')!==job.runToken)return Response.json({error:'Forbidden.'},{status:403});
  if(job.status!=='queued')return Response.json({ok:true,status:job.status||'unknown'});
  const apiKey=secrets.get('ASTRA_OPENAI_API_KEY');if(!apiKey)return Response.json({error:'Astra credentials are missing.'},{status:503});
  const {accessToken:githubToken}=await base44.asServiceRole.connectors.getConnection('github');const service=base44.asServiceRole,started=Date.now(),now=new Date().toISOString();
  const repoState=await inspectRepoState(githubToken,'doji0x/kydosv1',job.branch||'astra/latest');
  const previous=job.resumeFromJobId?await service.entities.AstraJob.get(job.resumeFromJobId).catch(()=>null):null;
  const handoff=resumeHandoff(previous,repoState);
  await service.entities.AstraJob.update(job.id,{status:'running',startedAt:now,heartbeatAt:now,baseCommitSha:repoState.baseCommitSha,headCommitSha:repoState.headSha,changedFiles:repoState.changedFiles||[],currentStep:0,currentStepLabel:'Repository state inspected',lastCheckpoint:handoff,nextStep:'Continue from the last verified state.',blocker:'',error:''});
  const writeMessage=data=>service.entities.AstraMessage.create({conversationId:job.conversationId,role:'activity',jobId:job.id,specialistRole:job.role,repo:'doji0x/kydosv1',...data});
  await writeMessage({activityType:'specialist_start',status:'running',content:`${job.jobUid} started`,summary:`${job.role} started after repository inspection`,detail:handoff.slice(0,ASTRA_LIMITS.event)});
  const decision=job.auditDecisionId?await service.entities.AstraAuditIssue.get(job.auditDecisionId):null;let issueCount=0,step=0,changedFiles=[...(repoState.changedFiles||[])],checks=[];
  const recordAuditIssue=async args=>{const fields=validateFinding(args);const issue=await service.entities.AstraAuditIssue.create({...fields,conversationId:job.conversationId,status:'pending',...(decision?{parentIssueId:decision.id}:{})});issueCount++;if(decision)await service.entities.AstraAuditIssue.update(decision.id,{supersededBy:issue.id});return{recorded:true,issueId:issue.id};};
  const log=async item=>{step=Math.max(step+1,item.step||0);if(item.changedFile&&!changedFiles.includes(item.changedFile))changedFiles.push(item.changedFile);if(item.toolName)checks=[...checks,{name:item.toolName,result:item.failed?`failed: ${item.error}`:'passed'}].slice(-30);const checkpoint=String(item.detail||item.label).slice(0,ASTRA_LIMITS.event);const stamp=new Date().toISOString();await service.entities.AstraJob.update(job.id,{heartbeatAt:stamp,currentStep:step,currentStepLabel:String(item.label||'Working').slice(0,200),lastCheckpoint:checkpoint,changedFiles,checks,blocker:item.failed?String(item.error||'Blocked').slice(0,500):'',nextStep:String(item.nextStep||'Continue unfinished work.').slice(0,500),headCommitSha:item.changedFile?String(checkpoint.split('→')[1]||repoState.headSha).trim():repoState.headSha});const ref=detailFor(item.toolName,item.args||{});await writeMessage({activityType:item.kind||'tool',status:item.failed?'failed':'running',content:String(item.label||'Progress').slice(0,200),summary:checkpoint,detail:'',durationMs:item.durationMs||0,toolName:item.toolName||'',...ref});};
  const report=await runSpecialist({apiKey,toolsModel:resolveToolsModel(secrets.get('ASTRA_TOOLS_MODEL')),githubToken,base44:service,role:job.role,job:job.job,context:job.context||'',log,beforeWrite:args=>assertAuditWrite(service,job.conversationId,decision,args),recordAuditIssue,repoState,previousCheckpoint:previous?.lastCheckpoint||''});
  const completedAt=new Date().toISOString(),durationMs=Date.now()-started,summary=report.slice(0,ASTRA_LIMITS.event);
  await service.entities.AstraJob.update(job.id,{status:'completed',report:report.slice(0,ASTRA_LIMITS.report),summary,resultRecordedAt:completedAt,completedAt,heartbeatAt:completedAt,durationMs,currentStepLabel:'Result recorded',lastCheckpoint:summary,nextStep:'No unfinished step.',blocker:''});
  await writeMessage({activityType:'report',status:'completed',content:summary,summary:`${job.role} result recorded`,durationMs});
  await writeMessage({activityType:'specialist_complete',status:'completed',content:`${job.jobUid} completed`,summary:`Completed in ${(durationMs/1000).toFixed(1)}s`,durationMs});
  if(decision&&job.role==='audit'&&!issueCount)await service.entities.AstraAuditIssue.update(decision.id,{status:'resolved',runStatus:'completed',runError:''});
  const next=(await service.entities.AstraJob.filter({conversationId:job.conversationId,status:'blocked'},'created_date',1))[0];if(next)await service.entities.AstraJob.update(next.id,{status:'queued',queuedAt:new Date().toISOString(),blocker:'',nextStep:'Execution is ready to begin.'});
  return Response.json({ok:true,jobId:job.jobUid,status:'completed'});
 }catch(error){if(job){const current=await base44.asServiceRole.entities.AstraJob.get(job.id).catch(()=>job);const update={...failureUpdate(current,error),durationMs:current.startedAt?Date.now()-new Date(current.startedAt).getTime():0,blocker:String(error.message).slice(0,500)};await base44.asServiceRole.entities.AstraJob.update(job.id,update).catch(()=>{});await base44.asServiceRole.entities.AstraMessage.create({conversationId:job.conversationId,role:'activity',jobId:job.id,specialistRole:job.role,activityType:'specialist_failed',status:'failed',content:`${job.jobUid||job.id} failed`,summary:String(error.message).slice(0,ASTRA_LIMITS.event),durationMs:update.durationMs,repo:'doji0x/kydosv1'}).catch(()=>{});}return Response.json({error:error.message},{status:500});}
}