import React, { useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import MarketCandleChart from '@/components/solana/MarketCandleChart';
import useMarketCandles from '@/hooks/useMarketCandles';
import { CANDLE_INTERVALS } from '@/lib/marketCandles';
import { ageLabel, formatPrice, shortMint } from '@/lib/markets';

export default function ExternalMarketChart({ mint, symbol }) {
  const [interval, setInterval] = useState('1h'), [variant, setVariant] = useState('candles');
  const feed = useMarketCandles(mint, interval), { page, candles } = feed;
  const signIn = [401, 403].includes(feed.error?.status);
  return <section aria-label={`${symbol} interactive price chart`} className="mb-5 min-w-0 overflow-hidden rounded-2xl border border-border bg-card/70">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4">
      <div><h2 className="text-sm font-semibold">{symbol} / USD <span className="ml-2 font-mono text-primary">{formatPrice(candles.at(-1)?.close)}</span></h2><p className="mt-1 text-[11px] text-muted-foreground">{page ? `${page.pool.name} · ${ageLabel(page.fetchedAt, feed.now)}` : 'Historical price and volume'}</p></div>
      <div className="flex max-w-full flex-wrap items-center gap-2"><div aria-label="Candle interval" className="flex rounded-lg bg-background/70 p-1">{CANDLE_INTERVALS.map(item => <button key={item} type="button" aria-pressed={item === interval} onClick={() => setInterval(item)} className={`min-h-9 rounded-md px-2.5 text-xs ${interval === item ? 'bg-primary/15 text-primary' : 'text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div><label className="sr-only" htmlFor="market-chart-style">Chart style</label><select id="market-chart-style" value={variant} onChange={event => setVariant(event.target.value)} className="h-10 rounded-lg border border-border bg-background px-2 text-xs"><option value="candles">Candles</option><option value="line">Line</option></select><button type="button" aria-label="Refresh chart" disabled={feed.isFetching} onClick={() => feed.refetch()} className="flex h-10 w-10 items-center justify-center rounded-lg border border-border disabled:opacity-40"><RefreshCw className={`h-3.5 w-3.5 ${feed.isFetching ? 'animate-spin' : ''}`}/></button></div>
    </header>
    {feed.stale && candles.length > 0 && <p role="status" className="border-b border-amber-400/20 bg-amber-400/5 px-4 py-2 text-xs text-amber-200">Chart updates are delayed. Showing saved candles. {page?.warning || feed.error?.message}</p>}
    {candles.length > 0 ? <MarketCandleChart candles={candles} timeframe={interval} seriesKey={`gecko:${mint}:${page.pool.address}:${interval}:USD`} currency="USD" volumeCurrency="USD" variant={variant} onLoadOlder={feed.loadOlder} canLoadOlder={feed.hasMore && !feed.loadingOlder && !feed.historyError}/> : <div className="flex min-h-[390px] flex-col items-center justify-center gap-3 px-6 text-center"><p role="status" className="text-sm text-muted-foreground">{feed.isPending && !feed.error ? 'Loading price history…' : feed.error?.message || 'No trades are available in this candle window. Try a wider interval.'}</p>{signIn ? <Link to="/login" className="text-sm text-primary underline">Sign in</Link> : <button type="button" disabled={feed.isFetching} onClick={() => feed.refetch()} className="rounded-lg border border-border px-4 py-2 text-xs disabled:opacity-40">{feed.isFetching ? 'Loading…' : 'Retry chart'}</button>}</div>}
    <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border px-4 py-3 text-[11px] text-muted-foreground"><div><p>{page ? <><a href={`https://www.geckoterminal.com/solana/pools/${page.pool.address}`} target="_blank" rel="noopener noreferrer" className="underline underline-offset-2">GeckoTerminal · {shortMint(page.pool.address)}</a> · {candles.length} candles · Volume in USD</> : 'Data via GeckoTerminal'}</p><p className="mt-1">Pool prices may differ from Jupiter’s aggregated price. Drag to pan; scroll or pinch to zoom.</p>{feed.historyError && <p role="status" className="mt-2 text-amber-200">{feed.historyError}</p>}{feed.atHistoryLimit && <p className="mt-2">History limit reached for this view. Choose a wider interval to see further back.</p>}</div><button type="button" onClick={feed.loadOlder} disabled={!feed.hasMore || feed.loadingOlder} className="shrink-0 rounded-lg border border-border px-3 py-2 text-xs disabled:opacity-40">{feed.loadingOlder ? 'Loading older…' : 'Load older'}</button></footer>
  </section>;
}
