import React,{useEffect,useState} from 'react';
import { Link } from 'react-router-dom';
import { BookOpen,History,MessagesSquare,Plus,Sparkles,X } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import AstraChatPanel from '@/components/astra/AstraChatPanel';
import AstraConversationsPanel from '@/components/astra/AstraConversationsPanel';
import AstraJobsPanel from '@/components/astra/AstraJobsPanel';
import AstraReferencesPanel from '@/components/astra/AstraReferencesPanel';
import useAstraChat from '@/hooks/useAstraChat';
export default function AdminAstra(){const [user,setUser]=useState(),[tab,setTab]=useState('chat');const chat=useAstraChat();useEffect(()=>{base44.auth.me().then(setUser)},[]);if(!user)return <div className="flex min-h-[60vh] items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-4 border-border border-t-primary"/></div>;if(user.role!=='admin')return <div className="mx-auto max-w-md p-8 text-center"><h1 className="text-xl font-semibold">Admin access required</h1><Link to="/" className="mt-4 inline-block text-primary">Return home</Link></div>;return <div className="min-h-screen"><header className="sticky top-0 z-50 border-b border-border bg-background/90 backdrop-blur"><div className="mx-auto flex h-14 max-w-3xl items-center gap-2 px-3"><Link to="/" className="p-2"><X/></Link><div className="flex-1"><p className="font-mono text-[10px] tracking-[.3em] text-primary">ADMIN · ASTRA</p><h1 className="font-semibold">Repository agent</h1></div><Button size="sm" variant="outline" disabled={chat.busy} onClick={()=>{chat.reset();setTab('chat')}}><Plus/>New chat</Button></div></header><main className="mx-auto max-w-3xl px-4 pb-20"><Tabs value={tab} onValueChange={setTab}><TabsList className="sticky top-14 z-40 my-4 grid h-auto w-full grid-cols-4"><TabsTrigger className="px-2" value="chat"><Sparkles/>Chat</TabsTrigger><TabsTrigger className="px-2" value="chats"><MessagesSquare/>Chats</TabsTrigger><TabsTrigger className="px-2" value="jobs"><History/>Jobs</TabsTrigger><TabsTrigger className="px-2" value="references"><BookOpen/>Library</TabsTrigger></TabsList><TabsContent value="chat"><AstraChatPanel chat={chat}/></TabsContent><TabsContent value="chats"><AstraConversationsPanel activeId={chat.conversationId} onOpen={id=>{chat.open(id);setTab('chat')}}/></TabsContent><TabsContent value="jobs"><AstraJobsPanel/></TabsContent><TabsContent value="references"><AstraReferencesPanel/></TabsContent></Tabs></main></div>}