import React,{useState} from 'react';
import ReactMarkdown from 'react-markdown';
import { ChevronDown,ChevronRight,LoaderCircle } from 'lucide-react';
import { base44 } from '@/api/base44Client';

export default function AstraSpecialistBlock({items}){
 const [open,setOpen]=useState(false),[details,setDetails]=useState({}),[loading,setLoading]=useState('');
 const first=items[0],last=items[items.length-1],done=items.some(x=>x.activityType==='specialist_complete'),failed=items.some(x=>x.activityType==='specialist_failed');
 const load=async item=>{if(details[item.id])return;setLoading(item.id);const r=await base44.functions.invoke('astraDetail',{messageId:item.id});setDetails(x=>({...x,[item.id]:r.data.detail}));setLoading('')};
 return <div className="rounded-xl border border-primary/20 bg-card/70 text-sm"><button onClick={()=>setOpen(x=>!x)} className="flex w-full items-center gap-3 p-3 text-left"><span className="rounded-md bg-primary/10 px-2 py-1 font-mono text-[10px] font-semibold uppercase tracking-wider text-primary">{first.specialistRole}</span><span className="min-w-0 flex-1 truncate text-xs text-muted-foreground">{last.summary||first.content}</span>{!done&&!failed&&<LoaderCircle className="h-4 w-4 animate-spin text-primary"/>}{open?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button>{open&&<div className="space-y-3 border-t border-border p-3"><p className="text-xs"><span className="text-muted-foreground">Job · </span>{first.content}</p>{items.filter(x=>!['specialist_start','specialist_complete'].includes(x.activityType)).map(item=><div key={item.id} className="border-l border-border pl-3"><div className="flex items-center justify-between gap-2"><span className="font-mono text-[10px] uppercase text-muted-foreground">{item.activityType}{item.toolName?` · ${item.toolName}`:''}</span>{item.detailType&&item.detailType!=='none'&&<button className="text-xs text-primary" onClick={()=>load(item)}>{loading===item.id?'Loading…':details[item.id]?'Loaded':'View detail'}</button>}</div>{item.activityType==='report'?<div className="prose prose-invert mt-2 max-w-none text-sm"><ReactMarkdown>{item.content}</ReactMarkdown></div>:<p className="mt-1 text-xs text-foreground/80">{item.summary||item.content}</p>}{details[item.id]&&<pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-background p-3 font-mono text-[10px] text-muted-foreground">{JSON.stringify(details[item.id],null,2)}</pre>}</div>)}</div>}</div>;
}