import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { secrets } from 'base44:runtime';
import { buildHistory, nextTurn } from './memory.ts';
import { crewOrder } from './roles.ts';
import { ASTRA_LIMITS, assertAstraPayload, compactAstraPayload, compactForModel, managerPlanEffect, reportedJobState, scheduledLabel } from '../../shared/astraOrchestration.ts';
import { inspectRepoState } from '../../shared/astraGithub.ts';
import { callOpenAi, resolveModel } from '../../shared/astraOpenAi.ts';
import { createAuditSession } from './auditSession.ts';
const responseFormat={type:'json_schema',name:'astra_manager_reply',strict:true,schema:{type:'object',additionalProperties:false,properties:{reply:{type:'string'},replacePending:{type:'boolean'},jobs:{type:'array',maxItems:6,items:{type:'object',additionalProperties:false,properties:{role:{type:'string',enum:crewOrder},scope:{type:'string'},job:{type:'string'},context:{type:'string'}},required:['role','scope','job','context']}}},required:['reply','replacePending','jobs']}};
const systemPrompt=`You are Astra, the conversational engineering manager for Kydos. Treat an explicit request to build, implement, fix, or approve a milestone as approval for bounded autonomous execution of that milestone. Decompose approved work into the necessary implementation, focused tests, fixes, integration, audit, and concise documentation jobs without asking permission for routine file changes, dependencies, or refactoring inside scope. Ask a concise question and return no jobs only when protocol economics, spending, deployment, destructive operations, credentials, merge conflicts, or a major scope change remains unresolved. Questions, praise, discussion, and status requests always return an empty jobs array and replacePending false; they never pause, cancel, enqueue, or redirect work. Never say work is scheduled, running, or completed; the orchestration layer reports those states only after durable events. Redirects may set replacePending true only with explicit replacement implementation jobs, and running work is never cancelled automatically. Keep updates short and blocker-focused. Give each job a concise scope and order conflicting work serially. Specialists share astra/latest, resume from relevant checkpoints and upstream changes, trust unchanged recorded results, and use focused checks. Other agents use separate branches or worktrees; integration back into astra/latest is part of the approved task when checks pass and there are no conflicts. Never disable protections, force-push, or overwrite active work. If another agent commits orchestration changes to main, require commit SHA, changed files, test results, concise handoff, and any outside-Git deployment reference before dependent work.`;
export default async function(req:Request):Promise<Response>{try{
 if(req.method!=='POST')return Response.json({error:'Use POST.'},{status:405});const base44=createClientFromRequest(req);const user=await base44.auth.me().catch(()=>null);if(user?.role!=='admin')return Response.json({error:'Admin access required.'},{status:403});
 const input=await req.json().catch(()=>({}));const conversationId=String(input.conversationId||'').trim(),requestId=String(input.requestId||crypto.randomUUID()).trim().slice(0,200);if(!conversationId)return Response.json({error:'A conversation id is required.'},{status:400});if(input.decision&&!['approve','reject'].includes(input.decision))return Response.json({error:'Choose approve or reject.'},{status:400});
 const delivered=await base44.entities.AstraMessage.filter({conversationId,requestId},'-created_date',10);const priorReply=delivered.find(x=>x.role==='assistant');if(priorReply){const priorJobs=await base44.entities.AstraJob.filter({conversationId,requestId},'-created_date',20);return Response.json({reply:priorReply.content,jobs:priorJobs.length,duplicate:true},{headers:{'Cache-Control':'no-store'}});}if(delivered.some(x=>x.role==='user'))return Response.json({reply:'Request is already being processed.',jobs:0,duplicate:true},{status:202,headers:{'Cache-Control':'no-store'}});
 const prompt=input.decision?`Audit decision: ${input.decision} for issue ${input.issueId}.`:String(input.message||'').trim();if(!prompt||prompt.length>ASTRA_LIMITS.message)return Response.json({error:`Send a message up to ${ASTRA_LIMITS.message.toLocaleString()} characters.`},{status:400});
 const apiKey=secrets.get('ASTRA_OPENAI_API_KEY');if(!apiKey)return Response.json({error:'Astra credentials are missing.'},{status:503});const audit=await createAuditSession(base44,input,user);const stored=(await base44.entities.AstraMessage.filter({conversationId},'-created_date',300)).reverse();const turn=nextTurn(stored);
 const userMessage=await base44.entities.AstraMessage.create({conversationId,requestId,role:'user',content:prompt,turn,repo:'doji0x/kydosv1'});if(audit.decision?.status==='rejected'){const reply=await audit.revise(apiKey,resolveModel(secrets.get('ASTRA_OPENAI_MODEL')));await base44.entities.AstraMessage.create({conversationId,requestId,role:'assistant',content:reply,turn,repo:'doji0x/kydosv1'});return Response.json({reply,jobs:0});}
 const active=await base44.entities.AstraJob.filter({conversationId,status:{$in:['queued','running','blocked']}},'created_date',100);const globalExecutors=await base44.entities.AstraJob.filter({status:{$in:['queued','running']}},'created_date',100);const state=active.map(x=>({jobId:x.jobUid||x.id,role:x.role,state:reportedJobState(x),branch:x.branch||'astra/latest',sha:x.headCommitSha||x.baseCommitSha||'unknown',step:x.currentStep||0,checkpoint:x.lastCheckpoint||'',blocker:x.blocker||''}));
 const messages=[{role:'system',content:systemPrompt},{role:'system',content:`Current jobs: ${JSON.stringify(state)}. Audit status: ${audit.blocked?'open findings exist; continue approved milestone work and schedule audit last':'clear'}. ${audit.directive||''}`},...buildHistory(stored),{role:'user',content:compactForModel(`[#${turn}] ${prompt}`,`astra-message:${userMessage.id}`).content}];const result=await callOpenAi({apiKey,model:resolveModel(secrets.get('ASTRA_OPENAI_MODEL')),messages,responseFormat});const plan=JSON.parse(result.content||'{}');let reply=String(plan.reply||'I’m ready.');const jobs=(plan.jobs||[]).filter(x=>crewOrder.includes(x.role));const effect=managerPlanEffect(jobs,!!plan.replacePending);
 if(jobs.length){const preparedJobs=jobs.map(x=>compactAstraPayload(x,`astra-message:${userMessage.id}`));preparedJobs.forEach(assertAstraPayload);const {accessToken}=await base44.asServiceRole.connectors.getConnection('github');const repoState=await inspectRepoState(accessToken,'doji0x/kydosv1','astra/latest');const batchId=crypto.randomUUID(),milestoneId=crypto.randomUUID(),queuedAt=new Date().toISOString();const previousFailed=await base44.entities.AstraJob.filter({conversationId,status:'failed'},'-failedAt',50);const rows=preparedJobs.map((x,i)=>{const previous=previousFailed.find(p=>p.role===x.role);return{jobUid:crypto.randomUUID(),requestId,conversationId,batchId,milestoneId,turn,role:x.role,scope:String(x.scope||x.job).slice(0,500),job:String(x.job),context:String(x.context),artifactRefs:x.artifactRefs||[],status:'blocked',position:i,attempt:1,maxAttempts:3,runToken:crypto.randomUUID(),branch:'astra/latest',baseCommitSha:repoState.baseCommitSha,headCommitSha:repoState.headSha,queuedAt,currentStep:0,currentStepLabel:'Awaiting execution',lastCheckpoint:previous?.lastCheckpoint||'',changedFiles:Array.from(new Set([...(repoState.changedFiles||[]),...(previous?.changedFiles||[])])),checks:previous?.checks||[],blocker:'Waiting for prior work.',nextStep:'Inspect repository state before execution.',...(previous?{resumeFromJobId:previous.id}:{}),...(audit.decision?{auditDecisionId:audit.decision.id}:{})};});
  const created=await base44.entities.AstraJob.bulkCreate(rows);try{if(effect.cancelPending){const old=active.filter(x=>x.status!=='running');if(old.length)await base44.entities.AstraJob.bulkUpdate(old.map(x=>({id:x.id,status:'cancelled',cancelledAt:new Date().toISOString(),blocker:'Replaced by an explicit redirect.'})));}const hasExecutor=globalExecutors.length>0&&!effect.cancelPending;if(!hasExecutor)await base44.entities.AstraJob.update(created[0].id,{status:'queued',blocker:'',nextStep:'Execution is ready to begin.'});reply=`${reply}\n\n${scheduledLabel(true,jobs.length)}`;}catch(error){await base44.entities.AstraJob.deleteMany({batchId});throw error;}
 }
 await base44.entities.AstraMessage.create({conversationId,requestId,role:'assistant',content:reply,turn,repo:'doji0x/kydosv1'});return Response.json({reply,jobs:jobs.length},{headers:{'Cache-Control':'no-store'}});
 }catch(error){console.error('astraChat failure',error?.stack||error);return Response.json({error:error.message},{status:500});}
}