import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { secrets } from 'base44:runtime';
import { buildHistory, nextTurn } from './memory.ts';
import { crewOrder } from './roles.ts';
import { ASTRA_LIMITS, assertAstraPayload, managerPlanEffect, reportedJobState, scheduledLabel } from '../../shared/astraOrchestration.ts';
import { inspectRepoState } from '../../shared/astraGithub.ts';
import { callOpenAi, resolveModel } from '../../shared/astraOpenAi.ts';
import { createAuditSession } from './auditSession.ts';
const responseFormat={type:'json_schema',name:'astra_manager_reply',strict:true,schema:{type:'object',additionalProperties:false,properties:{reply:{type:'string'},replacePending:{type:'boolean'},jobs:{type:'array',maxItems:6,items:{type:'object',additionalProperties:false,properties:{role:{type:'string',enum:crewOrder},scope:{type:'string'},job:{type:'string'},context:{type:'string'}},required:['role','scope','job','context']}}},required:['reply','replacePending','jobs']}};
const systemPrompt=`You are Astra, the conversational engineering manager for Kydos. Questions, discussion, status requests, and conversational messages return an empty jobs array and replacePending false, even while work is active. Only explicit implementation requests enqueue work. Never say work is scheduled, started, or completed; the orchestration layer reports those words only after the corresponding durable event. Redirects may set replacePending true only when they include replacement jobs. Running work is never cancelled automatically. Give each job a concise scope. Specialists share astra/latest and must inspect upstream state and checkpoints before resuming. Other agents should work on separate branches or worktrees; if one commits to main, require its commit SHA, changed files, and concise handoff before scheduling dependent work.`;
export default async function(req:Request):Promise<Response>{try{
 if(req.method!=='POST')return Response.json({error:'Use POST.'},{status:405});const base44=createClientFromRequest(req);const user=await base44.auth.me().catch(()=>null);if(user?.role!=='admin')return Response.json({error:'Admin access required.'},{status:403});
 const input=await req.json().catch(()=>({}));const conversationId=String(input.conversationId||'').trim();if(!conversationId)return Response.json({error:'A conversation id is required.'},{status:400});if(input.decision&&!['approve','reject'].includes(input.decision))return Response.json({error:'Choose approve or reject.'},{status:400});
 const prompt=input.decision?`Audit decision: ${input.decision} for issue ${input.issueId}.`:String(input.message||'').trim();if(!prompt||prompt.length>ASTRA_LIMITS.message)return Response.json({error:`Send a message up to ${ASTRA_LIMITS.message.toLocaleString()} characters.`},{status:400});
 const apiKey=secrets.get('ASTRA_OPENAI_API_KEY');if(!apiKey)return Response.json({error:'Astra credentials are missing.'},{status:503});const audit=await createAuditSession(base44,input,user);const stored=(await base44.entities.AstraMessage.filter({conversationId},'-created_date',300)).reverse();const turn=nextTurn(stored);
 await base44.entities.AstraMessage.create({conversationId,role:'user',content:prompt,turn,repo:'doji0x/kydosv1'});if(audit.decision?.status==='rejected'){const reply=await audit.revise(apiKey,resolveModel(secrets.get('ASTRA_OPENAI_MODEL')));await base44.entities.AstraMessage.create({conversationId,role:'assistant',content:reply,turn,repo:'doji0x/kydosv1'});return Response.json({reply,jobs:0});}
 const active=await base44.entities.AstraJob.filter({conversationId,status:{$in:['queued','running','blocked']}},'created_date',100);const state=active.map(x=>({jobId:x.jobUid||x.id,role:x.role,state:reportedJobState(x),branch:x.branch||'astra/latest',sha:x.headCommitSha||x.baseCommitSha||'unknown',step:x.currentStep||0,checkpoint:x.lastCheckpoint||'',blocker:x.blocker||''}));
 const messages=[{role:'system',content:systemPrompt},{role:'system',content:`Current jobs: ${JSON.stringify(state)}. Audit gate: ${audit.blocked?'closed; jobs must be empty':'open'}. ${audit.directive||''}`},...buildHistory(stored),{role:'user',content:`[#${turn}] ${prompt}`}];const result=await callOpenAi({apiKey,model:resolveModel(secrets.get('ASTRA_OPENAI_MODEL')),messages,responseFormat});const plan=JSON.parse(result.content||'{}');let reply=String(plan.reply||'I’m ready.');const jobs=audit.blocked?[]:(plan.jobs||[]).filter(x=>crewOrder.includes(x.role));const effect=managerPlanEffect(jobs,!!plan.replacePending);
 if(jobs.length){jobs.forEach(assertAstraPayload);const {accessToken}=await base44.asServiceRole.connectors.getConnection('github');const repoState=await inspectRepoState(accessToken,'doji0x/kydosv1','astra/latest');const batchId=crypto.randomUUID(),queuedAt=new Date().toISOString();const previousFailed=await base44.entities.AstraJob.filter({conversationId,status:'failed'},'-failedAt',50);const rows=jobs.map((x,i)=>{const previous=previousFailed.find(p=>p.role===x.role);return{jobUid:crypto.randomUUID(),conversationId,batchId,turn,role:x.role,scope:String(x.scope||x.job).slice(0,500),job:String(x.job),context:String(x.context),status:'blocked',position:i,runToken:crypto.randomUUID(),branch:'astra/latest',baseCommitSha:repoState.baseCommitSha,headCommitSha:repoState.headSha,queuedAt,currentStep:0,currentStepLabel:'Awaiting execution',lastCheckpoint:previous?.lastCheckpoint||'',changedFiles:Array.from(new Set([...(repoState.changedFiles||[]),...(previous?.changedFiles||[])])),checks:previous?.checks||[],blocker:'Waiting for prior work.',nextStep:'Inspect repository state before execution.',...(previous?{resumeFromJobId:previous.id}:{}),...(audit.decision?{auditDecisionId:audit.decision.id}:{})};});
  const created=await base44.entities.AstraJob.bulkCreate(rows);try{if(effect.cancelPending){const old=active.filter(x=>x.status!=='running');if(old.length)await base44.entities.AstraJob.bulkUpdate(old.map(x=>({id:x.id,status:'cancelled',cancelledAt:new Date().toISOString(),blocker:'Replaced by an explicit redirect.'})));}const hasExecutor=active.some(x=>x.status==='queued'||x.status==='running')&&!effect.cancelPending;if(!hasExecutor)await base44.entities.AstraJob.update(created[0].id,{status:'queued',blocker:'',nextStep:'Execution is ready to begin.'});reply=`${reply}\n\n${scheduledLabel(true,jobs.length)}`;}catch(error){await base44.entities.AstraJob.deleteMany({batchId});throw error;}
 }
 await base44.entities.AstraMessage.create({conversationId,role:'assistant',content:reply,turn,repo:'doji0x/kydosv1'});return Response.json({reply,jobs:jobs.length},{headers:{'Cache-Control':'no-store'}});
 }catch(error){console.error('astraChat failure',error?.stack||error);return Response.json({error:error.message},{status:500});}
}