import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';
import { compactAstraPayload, failureUpdate, managerPlanEffect, resumeHandoff, scheduledLabel } from '../../shared/astraOrchestration.ts';
import { inspectRepoState } from '../../shared/astraGithub.ts';
export default async function(req:Request):Promise<Response>{const base44=createClientFromRequest(req),service=base44.asServiceRole,testId=`orchestration-test-${crypto.randomUUID()}`;try{const user=await base44.auth.me().catch(()=>null);if(user?.role!=='admin')return Response.json({error:'Admin access required.'},{status:403});const results=[];const check=(name,pass,detail='')=>results.push({name,pass:!!pass,detail});const now=new Date().toISOString(),common={conversationId:testId,batchId:testId,turn:1,role:'architect',scope:'orchestration verification',job:'verify orchestration',position:0,runToken:crypto.randomUUID(),branch:'astra/latest',queuedAt:now};
 const pending=await service.entities.AstraJob.create({...common,jobUid:crypto.randomUUID(),requestId:`${testId}-pending`,status:'blocked'}),running=await service.entities.AstraJob.create({...common,jobUid:crypto.randomUUID(),requestId:`${testId}-running`,status:'running',startedAt:now,heartbeatAt:now});const before=[pending.status,running.status];const conversational=managerPlanEffect([],true);const unchanged=await service.entities.AstraJob.filter({conversationId:testId},'created_date',10);check('conversational message preserves jobs',!conversational.enqueue&&!conversational.cancelPending&&before.every((status,index)=>unchanged[index]?.status===status),unchanged.map(x=>x.status).join(', '));
 const requestId=`${testId}-build`,enqueued=await service.entities.AstraJob.create({...common,jobUid:crypto.randomUUID(),requestId,status:'queued'});const persisted=await service.entities.AstraJob.get(enqueued.id);const scheduled=scheduledLabel(!!persisted?.id,1);check('durable enqueue precedes scheduled report',persisted.status==='queued'&&scheduled.includes('scheduled'),`${persisted.id} persisted before label`);
 const failedUpdate=failureUpdate({...persisted,lastCheckpoint:'commit abc verified',currentStep:7,changedFiles:['src/a.js']},'forced test failure');await service.entities.AstraJob.update(enqueued.id,failedUpdate);const failed=await service.entities.AstraJob.get(enqueued.id);const {accessToken}=await service.connectors.getConnection('github');const repoState=await inspectRepoState(accessToken,'doji0x/kydosv1','astra/latest');const handoff=resumeHandoff(failed,repoState);check('failed checkpoint retained and repository inspected',failed.lastCheckpoint==='commit abc verified'&&failed.currentStep===7&&handoff.includes(`${repoState.branch}@${repoState.headSha}`),handoff);
 const artifact=await service.entities.AstraMessage.create({conversationId:testId,requestId:`${testId}-artifact`,role:'user',content:'x'.repeat(12050),turn:2,repo:'doji0x/kydosv1'});const compacted=compactAstraPayload({job:'x'.repeat(12050),context:''},`astra-message:${artifact.id}`);check('oversized content becomes artifact reference',compacted.job.length<=12000&&compacted.artifactRefs[0]===`astra-message:${artifact.id}`&&compacted.job.includes('[Full content:'),compacted.artifactRefs[0]);
 const duplicateCount=(await service.entities.AstraJob.filter({conversationId:testId,requestId},'created_date',20)).length;const retryRequestId=`${requestId}-retry`,retry=await service.entities.AstraJob.create({...common,jobUid:crypto.randomUUID(),requestId:retryRequestId,status:'blocked',resumeFromJobId:failed.id,lastCheckpoint:failed.lastCheckpoint});const retryCount=(await service.entities.AstraJob.filter({conversationId:testId,requestId:retryRequestId},'created_date',20)).length;check('duplicate suppressed and intentional retry accepted',duplicateCount===1&&retryCount===1&&retry.resumeFromJobId===failed.id,`duplicate=${duplicateCount}, retry=${retryCount}`);
 return Response.json({ok:results.every(x=>x.pass),commitSha:repoState.headSha,baseCommitSha:repoState.baseCommitSha,branch:repoState.branch,changedFiles:repoState.changedFiles||[],results,configurationChanges:['AstraJob.requestId is required for new jobs','AstraMessage.requestId stores delivery identity','Client sends a fresh requestId for intentional retries'],limitations:['Repository inspection covers remote GitHub state, not uncommitted local worktrees.']});}catch(error){return Response.json({error:error.message},{status:500});}finally{await service.entities.AstraJob.deleteMany({conversationId:testId}).catch(()=>{});await service.entities.AstraMessage.deleteMany({conversationId:testId}).catch(()=>{});}}